os:
  - osx
language: generic
sudo: required
dist: bionic
osx_image: xcode11
addons:
  homebrew:
    update: true
    packages:
      - pkg-config
      - assimp
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then eval "$(make copyMacPkgConfig501)"; fi # Temporary fix for assimp issue <https://github.com/assimp/assimp/issues/3174>
script:
  - swift package reset
  - swift build
  - swift test